version: '2'

networks:
  ros:
    driver: bridge

services:

  gazebo:
    image: rhysmainwaring/sail-sim-sitl
    devices:
      - /dev/dri
    environment:
      - "DISPLAY"
      - "SVGA_VGPU10=0"
    group_add:
      - video
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: stdbuf -o L gazebo /catkin_ws/install/share/rs750_gazebo/worlds/triangle_course_ocean.world --verbose
    # command: stdbuf -o L gazebo
    networks:
      - ros
    restart: always


  # sitl:
  #   image: rhysmainwaring/sail-sim-sitl
  #   devices:
  #     - /dev/dri
  #   environment:
  #     - "DISPLAY"
  #   group_add:
  #     - video
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix:rw
  #   # command: sim_vehicle.py -v Rover -f sailboat -L Mumbles --map --console
  #   command: python
  #   networks:
  #     - ros
  #   restart: always
